services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_pass123
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - fintech-data:/var/lib/postgresql/data
    networks:
      - fintech-network


  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - fintech-network

   
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    args:
      - REACT_APP_API_URL=http://backend:3001
    networks:
      - fintech-network

  volumes:
    fintech-data:
  networks:
    fintech-network:
      driver: bridge