services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: fintech_user
      POSTGRES_PASSWORD: fintech_pass123
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - fintech-data:/var/lib/postgresql

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: fintech_db
      DB_USER: fintech_user
      DB_PASSWORD: fintech_pass123
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://3.90.149.170:3001
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  fintech-data:
      driver: bridge
