grafana:
  service:
    type: NodePort
    nodePort: 31668

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: "30s"
    evaluationInterval: "30s"
    retention: "3h"
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "300Mi"
