#creamos nuestra imagen en GHCR (GitHub Container Registry) y la desplegamos en Kubernetes usando kubectl apply -f kubernetes/ para aplicar los manifiestos de Kubernetes que hemos creado, y luego hacemos un rollout restart para reiniciar el deployment y que coja la nueva imagen. Es importante configurar el kubeconfig con el secreto que hemos creado en GitHub Actions para poder acceder al cluster de Kubernetes desde la acción.

name: Build and Deploy Frontend Image

on:
  push:
    branches:
      - main


jobs:

  docker:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
          --build-arg REACT_APP_API_URL=http://44.211.144.11:30081 \
          -t ghcr.io/suecodingm/app-frontend:latest ./frontend

    - name: Push Docker image
      run: |
        docker push ghcr.io/suecodingm/app-frontend:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Create namespace
      run: |
        kubectl create namespace app-tfm --dry-run=client -o yaml | kubectl apply -f -


    - name: Deploy to Kubernetes
      run: |
        find kubernetes -type f
        kubectl apply -R -f kubernetes/

    - name: Restart deployment
      run: |
        kubectl rollout restart deployment/frontend -n app-tfm
