name: Adding Monitoring with Prometheus anda Gaafana

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Instalar Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.12.0'

    - name: Agregar Repositorio de Prometheus
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Mostrar values-finops
      run: |
        cat monitoring/values-finops.yml

    - name: Verificar directorio
      run: |
        pwd
        ls -R
    - name: Desplegar Stack Optimizado con Helm
      run: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          -f monitoring/values-finops.yml
