name: Build and Deploy Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/**'
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Instalar Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.12.0'

    - name: Agregar Repositorio de Prometheus
      run: |
        helm repo add prometheus-community https://github.io
        helm repo update

    - name: Desplegar Stack Optimizado con Helm
      run: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          -f monitoring/values-finops.yaml
