#para el volumen persistente
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namspace: app-tfm

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
