apiVersion: v1
kind: Secret

metadata:
  namespace: fintech
  name: postgres-secret

type: Opaque

stringData:
  POSTGRES_USER: fintech_user
  POSTGRES_PASSWORD: password_123.
  POSTGRES_DB: app_fintech_db
