#generamos el servicio de la base de datos, que es de tipo ClusterIP, lo que significa que solo es accesible dentro del cluster de Kubernetes. El servicio selecciona los pods que tienen la etiqueta app: postgres, y expone el puerto 5432, que es el puerto por defecto de PostgreSQL. De esta forma, el backend puede conectarse a la base de datos usando el nombre del servicio postgres-service y el puerto 5432.
apiVersion: v1
kind: Service

metadata:
  namespace: app-tfm
  name: postgres-service

spec:
  selector:
    app: postgres

  ports:
    - port: 5432
      targetPort: 5432

  type: ClusterIP
